In [1]:
from warnings import filterwarnings
filterwarnings('ignore')
import os
os.chdir('D:/py/')

In [2]:
import pandas as pd
df= pd.read_csv('spam.csv')
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will �_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
df.shape

(5572, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [5]:
df.describe(include='all')

v1                      v2  \
count   5572                    5572   
unique     2                    5169   
top      ham  Sorry, I'll call later   
freq    4825                      30   

                                               Unnamed: 2 Unnamed: 3  \
count                                                  50         12   
unique                                                 43         10   
top      bt not his girlfrnd... G o o d n i g h t . . .@"         GE   
freq                                                    3          2   

       Unnamed: 4  
count           6  
unique          5  
top       GNT:-)"  
freq            2

In [6]:
data = df[['v1', 'v2']]
data.columns = ['label', 'text']

In [7]:
data

label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
data.head()

label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [33]:
df.corr()

Empty DataFrame
Columns: []
Index: []

In [9]:
x=data['text']
y=data['label']

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
encoder = OneHotEncoder(sparse=False, drop='first')
y = encoder.fit_transform(data[["label"]])
y

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [12]:
tf=TfidfVectorizer()
x1=tf.fit_transform(x).toarray()         #text to numeric    Tfidf
x1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x1, y, test_size=0.21, random_state=62)

In [14]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
y_train

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [16]:
from sklearn.linear_model import LogisticRegression
lo=LogisticRegression()

In [17]:
lo.fit(x_train,y_train)

LogisticRegression()

In [18]:
y_pred_train=lo.predict(x_train)
y_pred_train

array([0., 0., 0., ..., 0., 0., 0.])

In [19]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

acc=accuracy_score(y_pred_train,y_train)
print('Accuracy_Score=',acc)

clr=classification_report(y_pred_train,y_train)
print('Classification_report=\n',clr)

cnf=confusion_matrix(y_pred_train,y_train)
print('Confusion_matrix= \n',cnf)

Accuracy_Score= 0.9731879118382186
Classification_report=
               precision    recall  f1-score   support

         0.0       1.00      0.97      0.98      3915
         1.0       0.81      1.00      0.89       486

    accuracy                           0.97      4401
   macro avg       0.90      0.98      0.94      4401
weighted avg       0.98      0.97      0.97      4401

Confusion_matrix= 
 [[3799  116]
 [   2  484]]


In [20]:
y_pred_test=lo.predict(x_test)
y_pred_test

array([0., 0., 0., ..., 1., 0., 0.])

In [21]:

acc1=accuracy_score(y_pred_test,y_test)
print('Accuracy_Score=',acc1)

clr1=classification_report(y_pred_test,y_test)
print('Classification_report=\n',clr1)

cnf1=confusion_matrix(y_pred_test,y_test)
print('Confusion_matrix= \n',cnf1)

Accuracy_Score= 0.968403074295474
Classification_report=
               precision    recall  f1-score   support

         0.0       1.00      0.97      0.98      1061
         1.0       0.75      1.00      0.86       110

    accuracy                           0.97      1171
   macro avg       0.87      0.98      0.92      1171
weighted avg       0.98      0.97      0.97      1171

Confusion_matrix= 
 [[1024   37]
 [   0  110]]


In [27]:
if prob > 0.5:
    print('spam')
else:
    print('no-spam')

spam


In [32]:
# unseen data

text=input('Enter the text =  ')
print(text)
print('--'*20)

x_text=tf.transform([text])
print('TFID = \n',x_text)
print('--'*20)

model=lo.predict(x_text)
print('Model= ',model)

if model > 0.5:
    print('spam')
else:
    print('no-spam')
    
print('--'*20)    
print('--'*20)

prob=lo.predict_proba(x_text)[:, 1].item() 
print('probability',prob)

if prob > 0.5:
    print('spam')
else:
    print('no-spam')
    

Enter the text =  Subject: message from john martin  - - - - - forwarded by cindy derecskey / corp / enron on 10 / 26 / 2000 06 : 32 am - - - - -  " john martin "  10 / 25 / 2000 06 : 58 pm  to :  cc :  subject : re : enron case study  cindy ,  great to hear from you and i look forward to getting our interviews done . i  am answering this from a hotel in seattle so i don ' t have questions for you  at this time but can get them together for you . i will contact vince next  week and get a set of questions together for each of the three individuals  you mentioned . i will have to talk to vince about others who would be of  interest to interview . i really appreciate your help in getting this  together and i ' ll work hard to get everything together for you next week . i  don ' t have vince ' s e - mail address with me here so i would appreciate your  forwarding this message on to him for me .  thanks again ,  john  - - - - - original message - - - - -  from : cindy . derecskey @ enron . 